# core/modules/naming/rules/unity_naming_rules.py
#
# Unity Asset Naming Rules — ShintTools Naming Validator
#
# Engine-specific counterparts to the three UE5 rules that depend on
# prefix / folder tables. Every other rule in ue5_naming_rules
# (case, special chars, duplicates, length, etc.) is engine-agnostic
# and is reused as-is by the orchestrator.
#
# Convention: UE5-clone style adapted to Unity's C# type names. The
# plugin sends asset_type from AssetDatabase.GetMainAssetTypeAtPath(...)
# which returns the bare C# class name ("Texture2D", "Material",
# "GameObject" for prefabs, "ScriptableObject", "AnimationClip", ...).
#
# Rule IDs:
#   NMU001 — detect_unity_missing_prefix          : asset lacks required prefix
#   NMU009 — detect_unity_wrong_folder            : asset_type does not match folder
#   NMU016 — detect_unity_wrong_prefix_for_type   : valid prefix but wrong for type

from pathlib import Path
from typing import Any, Dict, List, Optional

Issue = Dict[str, Any]
AssetRecord = Dict[str, str]


# ---------------------------------------------------------------------------
# _UNITY_TYPE_TO_PREFIX
#
# Maps Unity asset C# type name → expected name prefix (without the
# trailing underscore). The launcher's plugin sends type values like
# "Texture2D", "Material", "GameObject" (for prefabs), etc.
# ---------------------------------------------------------------------------

_UNITY_TYPE_TO_PREFIX: Dict[str, str] = {
    "AudioClip": "A",
    "AudioMixerController": "AM",
    "AnimationClip": "AN",
    "AnimationController": "ANC",
    "Font": "F",
    "Material": "M",
    "GameObject": "P",  # prefabs come through as GameObject
    "Mesh": "SM",  # imported 3D models (.obj, .fbx, .blend, etc.)
    "PhysicsMaterial": "PM",
    "PhysicsMaterial2D": "PM2",
    "RenderTexture": "RT",
    "SceneAsset": "S",
    "ScriptableObject": "SO",
    "ScriptGraphAsset": "SG",  # Unity Visual Scripting
    "Shader": "SH",
    "StateGraphAsset": "STG",  # Unity Visual Scripting
    "Texture2D": "T",
    "StyleSheet": "US",  # UI Toolkit
    "VisualTreeAsset": "UX",  # UI Toolkit
}


# ---------------------------------------------------------------------------
# _UNITY_TYPE_TO_FOLDER
#
# Maps Unity asset type → expected folder segment (lowercase). Used by
# detect_unity_wrong_folder. Only types where the convention is
# unambiguous are listed; types missing from this map skip the check
# rather than flag a false positive.
# ---------------------------------------------------------------------------

_UNITY_TYPE_TO_FOLDER: Dict[str, str] = {
    "AudioClip": "audio",
    "AudioMixerController": "audio",
    "AnimationClip": "animations",
    "AnimationController": "animators",
    "Font": "fonts",
    "Material": "materials",
    "GameObject": "prefabs",  # .prefab files
    "Mesh": "meshes",  # imported 3D models
    "PhysicsMaterial": "physics",
    "PhysicsMaterial2D": "physics",
    "RenderTexture": "rendertextures",
    "SceneAsset": "scenes",
    "ScriptableObject": "scriptableobjects",
    "ScriptGraphAsset": "visualscripting",
    "Shader": "shaders",
    "StateGraphAsset": "visualscripting",
    "Texture2D": "textures",
    "StyleSheet": "ui",
    "VisualTreeAsset": "ui",
}


# Cached reverse lookup: every prefix value that's a legitimate prefix
# for SOME type. Used by detect_unity_wrong_prefix_for_type to tell apart
# "no prefix" from "valid prefix but for a different type".
_KNOWN_PREFIXES: set = {prefix for prefix in _UNITY_TYPE_TO_PREFIX.values()}

# AssetDatabase.GetMainAssetTypeAtPath() returns "GameObject" for both
# Prefabs (.prefab) and imported 3D mesh files (.obj, .fbx, .blend, etc.).
# The core disambiguates via the file extension so each gets the right prefix:
#   .prefab              → GameObject (P_)
#   mesh extensions below → Mesh (SM_)
# Unity native extensions that use mixed case by design — these are
# generated by Unity itself and cannot/should not be renamed by the user.
# NMU012 (uppercase extension) must skip them to avoid false positives.
_UNITY_NATIVE_MIXED_CASE_EXTENSIONS: frozenset = frozenset(
    {
        ".physicMaterial",
        ".physicsMaterial2D",
        ".renderTexture",
        ".animatorController",
        ".overrideController",
        ".spriteatlas",
    }
)

_PREFAB_EXTENSION = ".prefab"
_MESH_EXTENSIONS: frozenset = frozenset(
    {".obj", ".fbx", ".blend", ".dae", ".3ds", ".dxf", ".max", ".mb", ".ma"}
)


def _resolve_gameobject_type(asset_path: str) -> str:
    """Disambiguate the 'GameObject' asset_type using the file extension.

    AssetDatabase.GetMainAssetTypeAtPath() returns 'GameObject' for both
    Prefabs and imported 3D mesh files. This helper returns the effective
    logical type so the naming rules can apply the correct prefix:

        .prefab          → 'GameObject'  (prefix P_)
        mesh extension   → 'Mesh'        (prefix SM_)
        anything else    → ''            (skip — unknown sub-type)
    """
    extension = Path(asset_path).suffix.lower()
    if extension == _PREFAB_EXTENSION:
        return "GameObject"
    if extension in _MESH_EXTENSIONS:
        return "Mesh"
    return ""


def _name_of(asset_path: str) -> str:
    return Path(asset_path).stem


def _emit(
    rule_id: str,
    asset_path: str,
    asset_type: str,
    message: str,
    fix_suggestion: Optional[str] = None,
) -> Issue:
    return {
        "rule_id": rule_id,
        "severity": "warning",
        "asset_path": asset_path,
        "asset_type": asset_type,
        "message": message,
        "fix_suggestion": fix_suggestion or "",
        "is_auto_fixable": bool(fix_suggestion),
    }


# ── NMU001 ──────────────────────────────────────────────────────────────────


def detect_unity_missing_prefix(records: List[AssetRecord]) -> List[Issue]:
    """Asset lacks the Unity prefix convention for its type.

    e.g. a Texture2D named `Hero.png` should be `T_Hero.png`. Skipped
    when asset_type is not in _UNITY_TYPE_TO_PREFIX (unknown / first-party
    asset types we don't map).

    Special case — GameObject: AssetDatabase.GetMainAssetTypeAtPath()
    returns "GameObject" for both Prefabs (.prefab) and imported meshes
    (.obj, .fbx, .blend, …). Only .prefab files are real Prefabs and
    should be flagged with O_; mesh files are silently skipped.
    """
    issues: List[Issue] = []
    for record in records:
        type_name = (record.get("asset_type") or "").strip()
        asset_path = record.get("asset_path", "")
        # GameObject is ambiguous — resolve to actual logical type via extension.
        if type_name == "GameObject":
            type_name = _resolve_gameobject_type(asset_path)
            if not type_name:
                continue
        required_prefix = _UNITY_TYPE_TO_PREFIX.get(type_name)
        if not required_prefix:
            continue
        asset_name = _name_of(asset_path)
        if not asset_name:
            continue
        # Skip names with no alphanumeric characters (e.g. "___") — the
        # fix would produce a worse name like "T____" with no semantic value.
        if not any(char.isalnum() for char in asset_name):
            continue
        # Already correctly prefixed?
        if asset_name.startswith(required_prefix + "_"):
            continue
        issues.append(
            _emit(
                "NMU001",
                record["asset_path"],
                type_name,
                f"{type_name} should start with `{required_prefix}_`"
                f" (got `{asset_name}`).",
                fix_suggestion=f"{required_prefix}_{asset_name}",
            )
        )
    return issues


# ── NMU009 ──────────────────────────────────────────────────────────────────


def detect_unity_wrong_folder(records: List[AssetRecord]) -> List[Issue]:
    """Asset stored in a folder that doesn't match the conventional
    location for its type.

    Detection: only flags when the asset is NOT under any path segment
    matching the expected folder name (case-insensitive). Doesn't
    enforce exact depth — `Assets/Game/Heroes/Textures/T_Hero.png` is
    fine for a Texture2D.
    """
    issues: List[Issue] = []
    for record in records:
        type_name = (record.get("asset_type") or "").strip()
        asset_path = record.get("asset_path") or ""
        # GameObject is ambiguous — resolve to actual logical type via extension.
        if type_name == "GameObject":
            type_name = _resolve_gameobject_type(asset_path)
            if not type_name:
                continue
        expected_folder = _UNITY_TYPE_TO_FOLDER.get(type_name)
        if not expected_folder:
            continue
        normalised_path = asset_path.lower().replace("\\", "/")
        path_segments = [segment for segment in normalised_path.split("/") if segment]
        # Skip the file name itself.
        if path_segments and path_segments[-1].endswith(
            (
                ".meta",
                ".asset",
                ".prefab",
                ".png",
                ".jpg",
                ".jpeg",
                ".fbx",
                ".mat",
                ".cs",
                ".controller",
                ".anim",
                ".wav",
                ".mp3",
                ".ogg",
                ".shader",
                ".shadergraph",
                ".vfx",
                ".unity",
            )
        ):
            path_segments = path_segments[:-1]
        if expected_folder in path_segments:
            continue
        issues.append(
            _emit(
                "NMU009",
                record["asset_path"],
                type_name,
                f"{type_name} is not stored under a `{expected_folder}` folder.",
            )
        )
    return issues


# ── NMU002 ──────────────────────────────────────────────────────────────────


def detect_unity_path_outside_assets(records: List[AssetRecord]) -> List[Issue]:
    """Asset path does not start with `Assets/`.

    Unity requires all project assets to live inside the Assets/ folder.
    Paths that don't start with Assets/ indicate an incorrect root, which
    causes AssetDatabase errors and platform builds to fail.
    """
    issues: List[Issue] = []
    for record in records:
        asset_path = (record.get("asset_path") or "").replace("\\", "/")
        if not asset_path:
            continue
        if not (asset_path.startswith("Assets/") or asset_path == "Assets"):
            issues.append(
                _emit(
                    "NMU002",
                    record["asset_path"],
                    record.get("asset_type", ""),
                    f"Asset path must start with `Assets/` (got `{asset_path}`).",
                )
            )
    return issues


# ── NMU003 ──────────────────────────────────────────────────────────────────


def detect_unity_backslash_in_path(records: List[AssetRecord]) -> List[Issue]:
    r"""Asset path uses backslash (`\`) instead of forward slash (`/`).

    Unity's AssetDatabase always uses forward slashes. Backslashes cause
    path resolution failures on macOS/Linux CI and in package builds.
    Replace every `\` with `/`.
    """
    issues: List[Issue] = []
    for record in records:
        asset_path = record.get("asset_path") or ""
        if "\\" in asset_path:
            fixed_path = asset_path.replace("\\", "/")
            issues.append(
                _emit(
                    "NMU003",
                    record["asset_path"],
                    record.get("asset_type", ""),
                    "Path contains backslashes; use forward slashes.",
                    fix_suggestion=fixed_path,
                )
            )
    return issues


# ── NMU004 ──────────────────────────────────────────────────────────────────

_VALID_SCRIPT_FOLDERS = {"scripts", "editor", "plugins", "runtime", "tests"}


def detect_unity_script_misplaced(records: List[AssetRecord]) -> List[Issue]:
    """C# script is not inside a Scripts/, Editor/, Plugins/, or Runtime/ folder.

    Loose .cs files at the Assets root or in art/audio folders break
    Assembly Definition boundaries and make compile order unpredictable.
    Move the script to the appropriate folder for its role.
    """
    issues: List[Issue] = []
    for record in records:
        asset_path = (record.get("asset_path") or "").replace("\\", "/")
        if not asset_path.lower().endswith(".cs"):
            continue
        folder_segments = [segment.lower() for segment in asset_path.split("/")[:-1]]
        if any(
            folder_segment in _VALID_SCRIPT_FOLDERS
            for folder_segment in folder_segments
        ):
            continue
        issues.append(
            _emit(
                "NMU004",
                record["asset_path"],
                record.get("asset_type", ""),
                "C# script is outside Scripts/, Editor/, Plugins/, or Runtime/.",
            )
        )
    return issues


# ── NMU005 ──────────────────────────────────────────────────────────────────


def detect_unity_resources_folder(records: List[AssetRecord]) -> List[Issue]:
    """Asset is stored under a Resources/ folder.

    Assets inside Resources/ are always included in the build and loaded
    into memory on startup, even if never referenced at runtime. Prefer
    Addressables or direct asset references to avoid bloating build size
    and memory usage.
    """
    issues: List[Issue] = []
    for record in records:
        asset_path = (record.get("asset_path") or "").replace("\\", "/")
        folder_segments = [segment.lower() for segment in asset_path.split("/")[:-1]]
        if "resources" in folder_segments:
            issues.append(
                _emit(
                    "NMU005",
                    record["asset_path"],
                    record.get("asset_type", ""),
                    "Asset is under Resources/; prefer Addressables or"
                    " direct references.",
                )
            )
    return issues


# ── NMU006 ──────────────────────────────────────────────────────────────────


def detect_unity_streaming_assets(records: List[AssetRecord]) -> List[Issue]:
    """Asset is stored under StreamingAssets/.

    Files there are copied verbatim into the build output and bypass
    Unity's asset pipeline (no compression, no type checking). Reserve
    StreamingAssets/ for data that must be read via raw file I/O at
    runtime (videos, external config). Everything else belongs under
    Assets/.
    """
    issues: List[Issue] = []
    for record in records:
        asset_path = (record.get("asset_path") or "").replace("\\", "/")
        folder_segments = [segment.lower() for segment in asset_path.split("/")[:-1]]
        if "streamingassets" in folder_segments:
            issues.append(
                _emit(
                    "NMU006",
                    record["asset_path"],
                    record.get("asset_type", ""),
                    "Asset is under StreamingAssets/; verify this is intentional.",
                )
            )
    return issues


# ── NMU007 ──────────────────────────────────────────────────────────────────

_EDITOR_ONLY_TYPES = {
    "DefaultAsset",
    "EditorBuildSettings",
    "EditorSettings",
    "BuildReport",
}


def detect_unity_editor_folder_misuse(records: List[AssetRecord]) -> List[Issue]:
    """Non-editor asset is stored inside an Editor/ folder.

    Assets under Editor/ are stripped from non-editor builds by Unity.
    Art assets, prefabs, ScriptableObjects, and other runtime assets
    placed here will be missing at runtime. Only .cs editor scripts and
    editor-specific asset types belong under Editor/.
    """
    issues: List[Issue] = []
    for record in records:
        asset_path = (record.get("asset_path") or "").replace("\\", "/")
        folder_segments = [segment.lower() for segment in asset_path.split("/")[:-1]]
        if "editor" not in folder_segments:
            continue
        type_name = (record.get("asset_type") or "").strip()
        if type_name in _EDITOR_ONLY_TYPES:
            continue
        if asset_path.lower().endswith(".cs"):
            continue
        issues.append(
            _emit(
                "NMU007",
                record["asset_path"],
                type_name,
                f"{type_name or 'Asset'} is under Editor/ and will be stripped"
                " from runtime builds.",
            )
        )
    return issues


# ── NMU008 ──────────────────────────────────────────────────────────────────


def detect_unity_scene_misplaced(records: List[AssetRecord]) -> List[Issue]:
    """Unity scene file is not stored under a Scenes/ folder.

    Scenes outside Scenes/ are harder to manage in Build Settings and
    break the standard Unity project layout expected by source-control
    and team workflows. Move the scene to Assets/Scenes/ or a subfolder.
    """
    issues: List[Issue] = []
    for record in records:
        type_name = (record.get("asset_type") or "").strip()
        if type_name != "SceneAsset":
            continue
        asset_path = (record.get("asset_path") or "").replace("\\", "/")
        folder_segments = [segment.lower() for segment in asset_path.split("/")[:-1]]
        if "scenes" in folder_segments:
            continue
        issues.append(
            _emit(
                "NMU008",
                record["asset_path"],
                type_name,
                "Scene is not under a Scenes/ folder.",
            )
        )
    return issues


# ── NMU010 ──────────────────────────────────────────────────────────────────

_SO_VALID_SUFFIXES = ("_Data", "_Config", "_Settings", "_Definition", "_Parameters")


def detect_unity_scriptableobject_suffix(records: List[AssetRecord]) -> List[Issue]:
    """ScriptableObject asset lacks a descriptive suffix (_Data, _Config, _Settings).

    ScriptableObjects serve as data containers and configuration holders.
    A suffix that describes their role (_Data, _Config, _Settings) makes
    their purpose immediately clear and avoids confusion with other asset
    types in the same folder.
    """
    issues: List[Issue] = []
    for record in records:
        type_name = (record.get("asset_type") or "").strip()
        if type_name != "ScriptableObject":
            continue
        asset_name = _name_of(record.get("asset_path", ""))
        if not asset_name:
            continue
        if any(asset_name.endswith(suffix) for suffix in _SO_VALID_SUFFIXES):
            continue
        suffix_list = ", ".join(f"`{suffix}`" for suffix in _SO_VALID_SUFFIXES[:3])
        issues.append(
            _emit(
                "NMU010",
                record["asset_path"],
                type_name,
                f"ScriptableObject `{asset_name}` should end with {suffix_list}, etc.",
                fix_suggestion=f"{asset_name}_Data",
            )
        )
    return issues


# ── NMU011 ──────────────────────────────────────────────────────────────────

_PBR_SUFFIXES = (
    "_Albedo",
    "_BaseColor",
    "_Normal",
    "_Metallic",
    "_Roughness",
    "_AO",
    "_MaskMap",
    "_Emissive",
    "_Height",
)


def detect_unity_texture_pbr_suffix(records: List[AssetRecord]) -> List[Issue]:
    """Texture2D asset has no PBR channel suffix (_Albedo, _Normal,
    _Metallic, etc.). Without one it's impossible to tell from the
    name whether a file is the albedo, normal map, or metallic map.
    Add a suffix matching the texture's role (_Albedo/_BaseColor,
    _Normal, _Metallic, _Roughness, _AO, _MaskMap, _Emissive).
    """
    issues: List[Issue] = []
    for record in records:
        type_name = (record.get("asset_type") or "").strip()
        if type_name != "Texture2D":
            continue
        asset_name = _name_of(record.get("asset_path", ""))
        if not asset_name:
            continue
        if any(asset_name.endswith(suffix) for suffix in _PBR_SUFFIXES):
            continue
        suffix_list = ", ".join(f"`{suffix}`" for suffix in _PBR_SUFFIXES[:4])
        issues.append(
            _emit(
                "NMU011",
                record["asset_path"],
                type_name,
                f"Texture `{asset_name}` is missing a PBR channel suffix"
                f" ({suffix_list}, …).",
            )
        )
    return issues


# ── NMU012 ──────────────────────────────────────────────────────────────────


def detect_unity_uppercase_extension(records: List[AssetRecord]) -> List[Issue]:
    """Asset file extension contains uppercase letters.

    Unity's import pipeline is case-sensitive on Linux (CI and Linux
    builds). `Hero.PNG` and `Hero.png` are the same asset on Windows
    but different on Linux, so this causes import failures that only
    show up in CI. Use a lowercase extension.
    """
    issues: List[Issue] = []
    for record in records:
        asset_path = record.get("asset_path") or ""
        extension = Path(asset_path).suffix
        if not extension:
            continue
        if extension == extension.lower():
            continue
        # Skip Unity native extensions that use mixed case by design.
        if extension in _UNITY_NATIVE_MIXED_CASE_EXTENSIONS:
            continue
        fixed_path = str(Path(asset_path).with_suffix(extension.lower())).replace(
            "\\", "/"
        )
        issues.append(
            _emit(
                "NMU012",
                record["asset_path"],
                record.get("asset_type", ""),
                f"Extension `{extension}` should be lowercase"
                f" `{extension.lower()}` (Linux/CI safety).",
                fix_suggestion=fixed_path,
            )
        )
    return issues


# ── NMU013 ──────────────────────────────────────────────────────────────────


def detect_unity_parent_dir_in_path(records: List[AssetRecord]) -> List[Issue]:
    """Asset path contains a parent-directory traversal (`..`).

    Paths with `..` components resolve to a location outside the folder
    they appear to be in, which breaks AssetDatabase lookups, addressable
    groups, and cross-platform builds. Normalise the path to remove all
    `..` segments.
    """
    issues: List[Issue] = []
    for record in records:
        asset_path = (record.get("asset_path") or "").replace("\\", "/")
        if ".." in asset_path.split("/"):
            issues.append(
                _emit(
                    "NMU013",
                    record["asset_path"],
                    record.get("asset_type", ""),
                    "Path contains `..` traversal segments;"
                    " use the canonical absolute path.",
                )
            )
    return issues


# ── NMU014 ──────────────────────────────────────────────────────────────────


def detect_unity_double_slash(records: List[AssetRecord]) -> List[Issue]:
    """Asset path contains consecutive forward slashes (`//`).

    Double slashes cause AssetDatabase.LoadAssetAtPath to fail silently —
    the asset exists on disk but cannot be found at runtime. This typically
    results from incorrect string concatenation when building paths
    programmatically. Collapse every `//` to a single `/`.
    """
    issues: List[Issue] = []
    for record in records:
        asset_path = (record.get("asset_path") or "").replace("\\", "/")
        if "//" in asset_path:
            fixed_path = asset_path
            while "//" in fixed_path:
                fixed_path = fixed_path.replace("//", "/")
            issues.append(
                _emit(
                    "NMU014",
                    record["asset_path"],
                    record.get("asset_type", ""),
                    "Path contains `//`; collapse to a single `/`.",
                    fix_suggestion=fixed_path,
                )
            )
    return issues


# ── NMU015 ──────────────────────────────────────────────────────────────────

_AUDIO_VALID_SUFFIXES = ("_SFX", "_Music", "_Ambient", "_VO", "_UI", "_Stinger")


def detect_unity_audio_missing_suffix(records: List[AssetRecord]) -> List[Issue]:
    """AudioClip asset lacks a category suffix (_SFX, _Music, _Ambient,
    _VO, _UI). Unity projects commonly organise audio by role —
    _SFX (sound effects), _Music (background tracks), _Ambient
    (environment loops), _VO (voice-over), _UI (interface feedback) —
    so the wrong clip doesn't get assigned to the wrong source.
    """
    issues: List[Issue] = []
    for record in records:
        type_name = (record.get("asset_type") or "").strip()
        if type_name != "AudioClip":
            continue
        asset_name = _name_of(record.get("asset_path", ""))
        if not asset_name:
            continue
        if any(asset_name.endswith(suffix) for suffix in _AUDIO_VALID_SUFFIXES):
            continue
        suffix_list = ", ".join(f"`{suffix}`" for suffix in _AUDIO_VALID_SUFFIXES[:4])
        issues.append(
            _emit(
                "NMU015",
                record["asset_path"],
                type_name,
                f"AudioClip `{asset_name}` is missing a category suffix"
                f" ({suffix_list}, …).",
            )
        )
    return issues


# ── NMU016 ──────────────────────────────────────────────────────────────────


def detect_unity_wrong_prefix_for_type(records: List[AssetRecord]) -> List[Issue]:
    """Name carries a known prefix but it's the wrong one for the asset
    type — e.g. a Material named `T_Concrete.mat` should be
    `M_Concrete.mat`.

    Skips assets with no prefix at all (NMU001 covers that) and
    asset_types we don't map.
    """
    issues: List[Issue] = []
    for record in records:
        type_name = (record.get("asset_type") or "").strip()
        asset_path = record.get("asset_path", "")
        # GameObject is ambiguous — resolve to actual logical type via extension.
        if type_name == "GameObject":
            type_name = _resolve_gameobject_type(asset_path)
            if not type_name:
                continue
        expected_prefix = _UNITY_TYPE_TO_PREFIX.get(type_name)
        if not expected_prefix:
            continue
        asset_name = _name_of(asset_path)
        if "_" not in asset_name:
            continue  # no prefix at all — NMU001 handles this case
        current_prefix = asset_name.split("_", 1)[0]
        if current_prefix == expected_prefix:
            continue
        if current_prefix not in _KNOWN_PREFIXES:
            continue  # not a recognised prefix; NMU001 will flag missing
        name_body = asset_name.split("_", 1)[1]
        issues.append(
            _emit(
                "NMU016",
                record["asset_path"],
                type_name,
                f"{type_name} uses prefix `{current_prefix}_`"
                f" but should use `{expected_prefix}_`.",
                fix_suggestion=f"{expected_prefix}_{name_body}",
            )
        )
    return issues
